[package]
name = "gstreamer_media"
version = "0.1.0"
authors = ["Marek G <no@mail.com>"]

[dependencies]
failure = "*"
gstreamer = "*"
gstreamer-app = "*"
gstreamer-gl-sys = { path = "../gstreamer-gl-sys", version = "*" }
glib = "*"

[build-dependencies]
pkg-config = "*"
